title: Ivan Zorić # your name (or website title) here
logo: "/images/PandaPredicament.jpg?raw=false" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Game developer:
  -Unity 3D C#
  <br><br>
  3D Artist:
  -Blender
  <br><br>
  Finished Machina Academy, Zagreb:
  -C# programming and Unity Game Engine
  <br><br>
  
  <br><br>
  Feel free to contact me on mobile: 
  +385 0989938110
  <br><br>
  or contact me on email: 
  cburstgames@gmail.com
  <br><br>
  <a href="https://www.linkedin.com/in/example/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
