title: Ivan Zorić # your name (or website title) here
logo: "/images/PandaPredicament.jpg?raw=false" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <h3><b>Level & Game designer/ 3D Artist:</b></h3>
  <i>Unity Game Engine
  <br>
  C#
  <br>
  Blender</i>
  <br><br>
  <h3><b>Finished Machina Academy, Zagreb:</b></h3>
  <i>C# programming and Unity Game Engine</i>
  <br>
  <br>
  <h3><b>Feel free to contact me:</b></h3>
  <u>Mobile:</u>
  <br>
  +385 98 993 8110
  <br><br>
  <u>Personal email:</u>
  <br>
  ivzoric88@gmail.com
  <br><br>
  <u>Game Studio email:</u>
  <br>
  cburstgames@gmail.com
  <br><br>
  <a href="https://cloudburst-games.itch.io/">Visit itch.io account of our Game Studio</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
